apiVersion: v1
kind: Service
metadata:
  name: cicd-python-ecs
  namespace: app
spec:
  selector:
    app: cicd-python-ecs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
